### ISSUE TITLE
Incorrect Atom feed location

### ISSUE THREAD

**Issue by evanrelf** [ayazhafiz/ayazhafiz.github.io#2]
Enjoyed hearing you and Richard talk about defunctionalization in Roc on the Software Unscripted podcast, went to check out your blog, but struggled to add it to my feed reader until I realized you made a typo in the code:

```diff
-<link rel="alternate" type="application/atom+xml" title="cc - Ayaz Hafiz" href="/feed-rrs2.xml">
+<link rel="alternate" type="application/atom+xml" title="cc - Ayaz Hafiz" href="/feed-rss2.xml">
```

**Comment by ayazhafiz** [comment]
Should be fixed now. Thank you!
